services:
  api: 
    build: .
    command: npm run start:dev
    restart: unless-stopped
    ports: 
      - "3001:3001"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=TestService
      - DB_HOST=0.0.0.0
      - DB_PORT=5432
      - API_PORT=8080
    depends_on:
      - postgres  
  postgres:
    image: postgres:9.6.20-alpine
    environment:
      - POSTGRES_USER=0.0.0.0
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=TestService
    ports: 
      - "5432:5432"
    volumes:
      - ./postgres_api:/var/lib/postgresql/data